ROOT_PATH = '/mnt/nas/Forest/MG-RAST_Dataset_Analysis'
DATABASE_PATH = '/db/target_gene_list.fasta'
MGRAST_DOWNLOAD_PATH = '/mnt/nas/bio_requests/9343/'
ALL_DATASETS = '/mnt/nas/bio_requests/9343/datasets.txt'
BBDUK_PATH = '/home/dussaultf/Applications/bbmap/'