DATABASE_PATH = '/mnt/nas/Forest/MG-RAST_Dataset_Analysis/db/target_gene_list.fasta'
CARB_DB_PATH = '/mnt/nas/Forest/MG-RAST_Dataset_Analysis/carbapenemase/carbapenemase_fasta_files/carbepenemase_merged.fasta'
MGRAST_DOWNLOAD_PATH = '/mnt/nas/bio_requests/9343/'
DATA_ANALYSIS_PATH = '/mnt/nas/Forest/MG-RAST_Dataset_Analysis/metagenomes/'
DATASET_ID_LIST = '/mnt/nas/bio_requests/9343/datasets.txt'
BBDUK_PATH = '/home/dussaultf/Applications/bbmap/'